### ISSUE TITLE
Mouse repositioning in UI mode

### ISSUE THREAD

**Issue by Azebu** [axjv/Input-Switcher#17] opened 2016-07-06 00:19 UTC
When you are in UI mode (for example when you open warp menu, might be only with the warp list addon), and buff/cooldown starts "blinking" (when 10 seconds are left), the mouse cursor will move to center of game screen, every time it blinks, every second. Happens even if ToS isn't the focused window.

**Comment by axjv** [comment] 2016-07-06 07:26
Can you list the other addons you have installed? Also, upload your settings file located in TreeofSavior/addons/cdtracker.

**Comment by Azebu** [comment] 2016-07-06 12:05
Here are my addons: http://puu.sh/pSckX.png
Here is my settings file: 
`{"skillPosX":1104,"buffPosY":179,"buffPosX":53,"chatList":[],"ignoreList":{"Gung Ho":true},"lock":true,"sound":true,"firstTimeMessage":true,"checkVal":3,"text":true,"message":[],"soundtype":5,"skin":1,"skills":true,"skillPosY":405,"buffs":true,"alerts":true,"size":0.8}`

**Comment by axjv** [comment] 2016-07-09 00:49
Try the latest version and let me know if you're still having problems.

**Comment by Azebu** [comment] 2016-07-12 00:43
Still the same issue.

**Comment by axjv** [comment] 2016-07-12 09:47
Made some more changes, I think it should be fixed.

**Comment by Azebu** [comment] 2016-07-12 16:54
Still the same issue.

**Comment by axjv** [comment] 2016-07-13 23:27
I was finally able to reproduce your issue on my machine, and it seems that this behavior is due to the way UI mode works. Essentially if it detects a frame being created/updated, it will center your mouse cursor. As such, until I find a better solution I've added a system to disable frame updates while UI mode is enabled.

Hope this solves your problem.

**Comment by Azebu** [comment] 2016-07-15 13:04
That works, thanks.

**Closed as completed** 2016-07-18 00:13 UTC
